apiVersion: v2
name: fluffy
description: A Helm chart for running fluffy alongside LakeFS on Kubernetes
type: application
version: 0.1.0
appVersion: "0.1.1"
home: https://lakefs.io
icon: https://lakefs.io/wp-content/uploads/2020/07/lake-fs-color-2.svg
sources:
  - https://github.com/treeverse/lakeFS
maintainers:
  - name: treeverse
    email: services@treeverse.io
