
authEncryptionKey: &authEncryptionKey "secret"
lakefs:
  enabled: true
  lakefsConfig: |
    database:
        type: local
    logging:
        level: "DEBUG"
    blockstore:
      type: local
    auth:
      encrypt:
        secret_key: secret
      oidc:
        friendly_name_claim_name: "name"
        default_initial_groups: ["Developers"]
      ui_config:
        login_url: /oidc/login
        logout_url: /oidc/logout
        login_cookie_names:
          - internal_auth_session
          - oidc_auth_session
        #rbac: external

  ingress:
    enabled: true
    ingressClassName: nginx-external
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        if ($http_x_forwarded_proto = 'http') {
          return 301 https://$host$request_uri;
        }
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/server-snippet: |
        location ~* "^/(metrics|_pprof)" {
            deny all;
            return 403;
          }
    hosts:
      - host: lakefs-rc.us-east-1.lakefscloud.ninja
        paths:
        - /
        pathsOverrides:
          - path: /oidc/
            serviceName: lakefs-fluffy-sso
            servicePort: 80
          - path: /api/v1/oidc/
            serviceName: lakefs-fluffy-sso
            servicePort: 80
fluffy:
  enabled: true
  secret: *authEncryptionKey